# Generated by Django 5.2.5 on 2025-08-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
