# Generated by Django 5.2.5 on 2025-08-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=200)),
                ('diagnoses', models.TextField()),
                ('disease', models.CharField(max_length=200)),
                ('lab_tests', models.TextField(blank=True, null=True)),
                ('medicine', models.TextField()),
            ],
        ),
    ]
