# Generated by Django 5.2.5 on 2025-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_branch', models.CharField(max_length=255)),
            ],
        ),
    ]
