# Generated by Django 5.2.5 on 2025-08-30 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0007_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default=500, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='drug',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='create_user.drug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=10),
        ),
    ]
