# Generated by Django 5.2.5 on 2025-08-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0008_prescription_dosage_prescription_drug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
