# Generated by Django 5.2.5 on 2025-08-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0009_alter_patient_bmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bmi',
        ),
    ]
