# Generated by Django 5.2.5 on 2025-08-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0012_emergency2'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency2',
            name='dnr',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
