# Generated by Django 5.2.5 on 2025-08-30 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0013_emergency2_dnr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='critical_notes',
        ),
    ]
