# Generated by Django 5.2.5 on 2025-08-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0014_remove_emergency_critical_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='blood_group',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='chronic_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='critical_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='dnr',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='emergency',
            name='prescriptions_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Emergency2',
        ),
    ]
