# Generated by Django 5.2.5 on 2025-09-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0016_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='critical_notes',
        ),
    ]
