# Generated by Django 5.2.5 on 2025-08-31 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('create_user', '0015_emergency_allergies_emergency_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('BMI', models.FloatField(default=0.0)),
                ('smoking', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('physical_activity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=10)),
                ('glucose', models.FloatField(default=90.0)),
                ('HbA1c', models.FloatField(default=5.0)),
                ('cholesterol', models.FloatField(default=180.0)),
                ('blood_pressure_systolic', models.FloatField(default=120.0)),
                ('blood_pressure_diastolic', models.FloatField(default=80.0)),
                ('creatinine', models.FloatField(default=1.0)),
                ('microalbuminuria', models.FloatField(default=0.0)),
                ('c_peptide', models.FloatField(default=2.0)),
                ('diabetes_in_family', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('previous_diagnoses', models.TextField(blank=True, null=True)),
                ('drug_history', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='create_user.patient')),
            ],
        ),
    ]
