# Generated by Django 5.2.5 on 2025-08-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfeatures',
            name='microalbuminuria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
