# Generated by Django 5.2.5 on 2025-08-31 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_alter_patientfeatures_microalbuminuria'),
        ('create_user', '0015_emergency_allergies_emergency_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('risk_level', models.CharField(max_length=50)),
                ('recommendation', models.TextField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='create_user.patient')),
            ],
        ),
    ]
